//package jcog.memoize.byt;
//
///** the parameter field is not propagated to generated ByteKeyInternal instances.
// * it is also explicitly forgotten (nulled) when this key is closed.
// */
//public abstract class ByteKeyExternalWithParameter<X> extends ByteKeyExternal {
//    public X x;
//
//    public ByteKeyExternalWithParameter(X x) {
//        this.x = x;
//    }
//
//    @Override
//    public void close() {
//        x = null;
//        super.close();
//    }
//}
