package spacegraph.input.key.impl;


import java.awt.event.KeyEvent;

public enum Keyboard { ;

//    /** from: https://github.com/JogAmp/jogl/blob/master/src/newt/classes/jogamp/newt/awt/event/AWTNewtEventFactory.java */
//    public static short awtKeyCode2NewtKeyCode(final int awtKeyCode) {
//        final short defNEWTKeyCode = (short)awtKeyCode;
//        switch (awtKeyCode) {
//            case java.awt.event.KeyEvent.VK_HOME          : return com.jogamp.newt.event.KeyEvent.VK_HOME;
//            case java.awt.event.KeyEvent.VK_END           : return com.jogamp.newt.event.KeyEvent.VK_END;
//            case java.awt.event.KeyEvent.VK_FINAL         : return com.jogamp.newt.event.KeyEvent.VK_FINAL;
//            case java.awt.event.KeyEvent.VK_PRINTSCREEN   : return com.jogamp.newt.event.KeyEvent.VK_PRINTSCREEN;
//            case java.awt.event.KeyEvent.VK_BACK_SPACE    : return com.jogamp.newt.event.KeyEvent.VK_BACK_SPACE;
//            case java.awt.event.KeyEvent.VK_TAB           : return com.jogamp.newt.event.KeyEvent.VK_TAB;
//            case java.awt.event.KeyEvent.VK_ENTER         : return com.jogamp.newt.event.KeyEvent.VK_ENTER;
//            case java.awt.event.KeyEvent.VK_PAGE_DOWN     : return com.jogamp.newt.event.KeyEvent.VK_PAGE_DOWN;
//            case java.awt.event.KeyEvent.VK_CLEAR         : return com.jogamp.newt.event.KeyEvent.VK_CLEAR;
//            case java.awt.event.KeyEvent.VK_SHIFT         : return com.jogamp.newt.event.KeyEvent.VK_SHIFT;
//            case java.awt.event.KeyEvent.VK_PAGE_UP       : return com.jogamp.newt.event.KeyEvent.VK_PAGE_UP;
//            case java.awt.event.KeyEvent.VK_CONTROL       : return com.jogamp.newt.event.KeyEvent.VK_CONTROL;
//            case java.awt.event.KeyEvent.VK_ALT           : return com.jogamp.newt.event.KeyEvent.VK_ALT;
//            case java.awt.event.KeyEvent.VK_ALT_GRAPH     : return com.jogamp.newt.event.KeyEvent.VK_ALT_GRAPH;
//            case java.awt.event.KeyEvent.VK_CAPS_LOCK     : return com.jogamp.newt.event.KeyEvent.VK_CAPS_LOCK;
//            case java.awt.event.KeyEvent.VK_PAUSE         : return com.jogamp.newt.event.KeyEvent.VK_PAUSE;
//            case java.awt.event.KeyEvent.VK_SCROLL_LOCK   : return com.jogamp.newt.event.KeyEvent.VK_SCROLL_LOCK;
//            case java.awt.event.KeyEvent.VK_CANCEL        : return com.jogamp.newt.event.KeyEvent.VK_CANCEL;
//            case java.awt.event.KeyEvent.VK_INSERT        : return com.jogamp.newt.event.KeyEvent.VK_INSERT;
//            case java.awt.event.KeyEvent.VK_ESCAPE        : return com.jogamp.newt.event.KeyEvent.VK_ESCAPE;
//            case java.awt.event.KeyEvent.VK_CONVERT       : return com.jogamp.newt.event.KeyEvent.VK_CONVERT;
//            case java.awt.event.KeyEvent.VK_NONCONVERT    : return com.jogamp.newt.event.KeyEvent.VK_NONCONVERT;
//            case java.awt.event.KeyEvent.VK_ACCEPT        : return com.jogamp.newt.event.KeyEvent.VK_ACCEPT;
//            case java.awt.event.KeyEvent.VK_MODECHANGE    : return com.jogamp.newt.event.KeyEvent.VK_MODECHANGE;
//            case java.awt.event.KeyEvent.VK_SPACE         : return com.jogamp.newt.event.KeyEvent.VK_SPACE;
//            case java.awt.event.KeyEvent.VK_EXCLAMATION_MARK: return com.jogamp.newt.event.KeyEvent.VK_EXCLAMATION_MARK;
//            case java.awt.event.KeyEvent.VK_QUOTEDBL      : return com.jogamp.newt.event.KeyEvent.VK_QUOTEDBL;
//            case java.awt.event.KeyEvent.VK_NUMBER_SIGN   : return com.jogamp.newt.event.KeyEvent.VK_NUMBER_SIGN;
//            case java.awt.event.KeyEvent.VK_DOLLAR        : return com.jogamp.newt.event.KeyEvent.VK_DOLLAR;
//            // case                         0x25             : return com.jogamp.newt.event.KeyEvent.VK_PERCENT;
//            case java.awt.event.KeyEvent.VK_AMPERSAND     : return com.jogamp.newt.event.KeyEvent.VK_AMPERSAND;
//            case java.awt.event.KeyEvent.VK_QUOTE         : return com.jogamp.newt.event.KeyEvent.VK_QUOTE;
//            case java.awt.event.KeyEvent.VK_LEFT_PARENTHESIS : return com.jogamp.newt.event.KeyEvent.VK_LEFT_PARENTHESIS;
//            case java.awt.event.KeyEvent.VK_RIGHT_PARENTHESIS: return com.jogamp.newt.event.KeyEvent.VK_RIGHT_PARENTHESIS;
//            case java.awt.event.KeyEvent.VK_ASTERISK      : return com.jogamp.newt.event.KeyEvent.VK_ASTERISK;
//            case java.awt.event.KeyEvent.VK_PLUS          : return com.jogamp.newt.event.KeyEvent.VK_PLUS;
//            case java.awt.event.KeyEvent.VK_COMMA         : return com.jogamp.newt.event.KeyEvent.VK_COMMA;
//            case java.awt.event.KeyEvent.VK_MINUS         : return com.jogamp.newt.event.KeyEvent.VK_MINUS;
//            case java.awt.event.KeyEvent.VK_PERIOD        : return com.jogamp.newt.event.KeyEvent.VK_PERIOD;
//            case java.awt.event.KeyEvent.VK_SLASH         : return com.jogamp.newt.event.KeyEvent.VK_SLASH;
//            case java.awt.event.KeyEvent.VK_0             : return com.jogamp.newt.event.KeyEvent.VK_0;
//            case java.awt.event.KeyEvent.VK_1             : return com.jogamp.newt.event.KeyEvent.VK_1;
//            case java.awt.event.KeyEvent.VK_2             : return com.jogamp.newt.event.KeyEvent.VK_2;
//            case java.awt.event.KeyEvent.VK_3             : return com.jogamp.newt.event.KeyEvent.VK_3;
//            case java.awt.event.KeyEvent.VK_4             : return com.jogamp.newt.event.KeyEvent.VK_4;
//            case java.awt.event.KeyEvent.VK_5             : return com.jogamp.newt.event.KeyEvent.VK_5;
//            case java.awt.event.KeyEvent.VK_6             : return com.jogamp.newt.event.KeyEvent.VK_6;
//            case java.awt.event.KeyEvent.VK_7             : return com.jogamp.newt.event.KeyEvent.VK_7;
//            case java.awt.event.KeyEvent.VK_8             : return com.jogamp.newt.event.KeyEvent.VK_8;
//            case java.awt.event.KeyEvent.VK_9             : return com.jogamp.newt.event.KeyEvent.VK_9;
//            case java.awt.event.KeyEvent.VK_COLON         : return com.jogamp.newt.event.KeyEvent.VK_COLON;
//            case java.awt.event.KeyEvent.VK_SEMICOLON     : return com.jogamp.newt.event.KeyEvent.VK_SEMICOLON;
//            case java.awt.event.KeyEvent.VK_LESS          : return com.jogamp.newt.event.KeyEvent.VK_LESS;
//            case java.awt.event.KeyEvent.VK_EQUALS        : return com.jogamp.newt.event.KeyEvent.VK_EQUALS;
//            case java.awt.event.KeyEvent.VK_GREATER       : return com.jogamp.newt.event.KeyEvent.VK_GREATER;
//            case                         0x3f             : return com.jogamp.newt.event.KeyEvent.VK_QUESTIONMARK;
//            case java.awt.event.KeyEvent.VK_AT            : return com.jogamp.newt.event.KeyEvent.VK_AT;
//            case java.awt.event.KeyEvent.VK_A             : return com.jogamp.newt.event.KeyEvent.VK_A;
//            case java.awt.event.KeyEvent.VK_B             : return com.jogamp.newt.event.KeyEvent.VK_B;
//            case java.awt.event.KeyEvent.VK_C             : return com.jogamp.newt.event.KeyEvent.VK_C;
//            case java.awt.event.KeyEvent.VK_D             : return com.jogamp.newt.event.KeyEvent.VK_D;
//            case java.awt.event.KeyEvent.VK_E             : return com.jogamp.newt.event.KeyEvent.VK_E;
//            case java.awt.event.KeyEvent.VK_F             : return com.jogamp.newt.event.KeyEvent.VK_F;
//            case java.awt.event.KeyEvent.VK_G             : return com.jogamp.newt.event.KeyEvent.VK_G;
//            case java.awt.event.KeyEvent.VK_H             : return com.jogamp.newt.event.KeyEvent.VK_H;
//            case java.awt.event.KeyEvent.VK_I             : return com.jogamp.newt.event.KeyEvent.VK_I;
//            case java.awt.event.KeyEvent.VK_J             : return com.jogamp.newt.event.KeyEvent.VK_J;
//            case java.awt.event.KeyEvent.VK_K             : return com.jogamp.newt.event.KeyEvent.VK_K;
//            case java.awt.event.KeyEvent.VK_L             : return com.jogamp.newt.event.KeyEvent.VK_L;
//            case java.awt.event.KeyEvent.VK_M             : return com.jogamp.newt.event.KeyEvent.VK_M;
//            case java.awt.event.KeyEvent.VK_N             : return com.jogamp.newt.event.KeyEvent.VK_N;
//            case java.awt.event.KeyEvent.VK_O             : return com.jogamp.newt.event.KeyEvent.VK_O;
//            case java.awt.event.KeyEvent.VK_P             : return com.jogamp.newt.event.KeyEvent.VK_P;
//            case java.awt.event.KeyEvent.VK_Q             : return com.jogamp.newt.event.KeyEvent.VK_Q;
//            case java.awt.event.KeyEvent.VK_R             : return com.jogamp.newt.event.KeyEvent.VK_R;
//            case java.awt.event.KeyEvent.VK_S             : return com.jogamp.newt.event.KeyEvent.VK_S;
//            case java.awt.event.KeyEvent.VK_T             : return com.jogamp.newt.event.KeyEvent.VK_T;
//            case java.awt.event.KeyEvent.VK_U             : return com.jogamp.newt.event.KeyEvent.VK_U;
//            case java.awt.event.KeyEvent.VK_V             : return com.jogamp.newt.event.KeyEvent.VK_V;
//            case java.awt.event.KeyEvent.VK_W             : return com.jogamp.newt.event.KeyEvent.VK_W;
//            case java.awt.event.KeyEvent.VK_X             : return com.jogamp.newt.event.KeyEvent.VK_X;
//            case java.awt.event.KeyEvent.VK_Y             : return com.jogamp.newt.event.KeyEvent.VK_Y;
//            case java.awt.event.KeyEvent.VK_Z             : return com.jogamp.newt.event.KeyEvent.VK_Z;
//            case java.awt.event.KeyEvent.VK_OPEN_BRACKET  : return com.jogamp.newt.event.KeyEvent.VK_OPEN_BRACKET;
//            case java.awt.event.KeyEvent.VK_BACK_SLASH    : return com.jogamp.newt.event.KeyEvent.VK_BACK_SLASH;
//            case java.awt.event.KeyEvent.VK_CLOSE_BRACKET : return com.jogamp.newt.event.KeyEvent.VK_CLOSE_BRACKET;
//            case java.awt.event.KeyEvent.VK_CIRCUMFLEX    : return com.jogamp.newt.event.KeyEvent.VK_CIRCUMFLEX;
//            case java.awt.event.KeyEvent.VK_UNDERSCORE    : return com.jogamp.newt.event.KeyEvent.VK_UNDERSCORE;
//            case java.awt.event.KeyEvent.VK_BACK_QUOTE    : return com.jogamp.newt.event.KeyEvent.VK_BACK_QUOTE;
//            case java.awt.event.KeyEvent.VK_F1            : return com.jogamp.newt.event.KeyEvent.VK_F1;
//            case java.awt.event.KeyEvent.VK_F2            : return com.jogamp.newt.event.KeyEvent.VK_F2;
//            case java.awt.event.KeyEvent.VK_F3            : return com.jogamp.newt.event.KeyEvent.VK_F3;
//            case java.awt.event.KeyEvent.VK_F4            : return com.jogamp.newt.event.KeyEvent.VK_F4;
//            case java.awt.event.KeyEvent.VK_F5            : return com.jogamp.newt.event.KeyEvent.VK_F5;
//            case java.awt.event.KeyEvent.VK_F6            : return com.jogamp.newt.event.KeyEvent.VK_F6;
//            case java.awt.event.KeyEvent.VK_F7            : return com.jogamp.newt.event.KeyEvent.VK_F7;
//            case java.awt.event.KeyEvent.VK_F8            : return com.jogamp.newt.event.KeyEvent.VK_F8;
//            case java.awt.event.KeyEvent.VK_F9            : return com.jogamp.newt.event.KeyEvent.VK_F9;
//            case java.awt.event.KeyEvent.VK_F10           : return com.jogamp.newt.event.KeyEvent.VK_F10;
//            case java.awt.event.KeyEvent.VK_F11           : return com.jogamp.newt.event.KeyEvent.VK_F11;
//            case java.awt.event.KeyEvent.VK_F12           : return com.jogamp.newt.event.KeyEvent.VK_F12;
//            case java.awt.event.KeyEvent.VK_F13           : return com.jogamp.newt.event.KeyEvent.VK_F13;
//            case java.awt.event.KeyEvent.VK_F14           : return com.jogamp.newt.event.KeyEvent.VK_F14;
//            case java.awt.event.KeyEvent.VK_F15           : return com.jogamp.newt.event.KeyEvent.VK_F15;
//            case java.awt.event.KeyEvent.VK_F16           : return com.jogamp.newt.event.KeyEvent.VK_F16;
//            case java.awt.event.KeyEvent.VK_F17           : return com.jogamp.newt.event.KeyEvent.VK_F17;
//            case java.awt.event.KeyEvent.VK_F18           : return com.jogamp.newt.event.KeyEvent.VK_F18;
//            case java.awt.event.KeyEvent.VK_F19           : return com.jogamp.newt.event.KeyEvent.VK_F19;
//            case java.awt.event.KeyEvent.VK_F20           : return com.jogamp.newt.event.KeyEvent.VK_F20;
//            case java.awt.event.KeyEvent.VK_F21           : return com.jogamp.newt.event.KeyEvent.VK_F21;
//            case java.awt.event.KeyEvent.VK_F22           : return com.jogamp.newt.event.KeyEvent.VK_F22;
//            case java.awt.event.KeyEvent.VK_F23           : return com.jogamp.newt.event.KeyEvent.VK_F23;
//            case java.awt.event.KeyEvent.VK_F24           : return com.jogamp.newt.event.KeyEvent.VK_F24;
//            case java.awt.event.KeyEvent.VK_BRACELEFT     : return com.jogamp.newt.event.KeyEvent.VK_LEFT_BRACE;
//            case                         0x7c             : return com.jogamp.newt.event.KeyEvent.VK_PIPE;
//            case java.awt.event.KeyEvent.VK_BRACERIGHT    : return com.jogamp.newt.event.KeyEvent.VK_RIGHT_BRACE;
//            case java.awt.event.KeyEvent.VK_DEAD_TILDE    : return com.jogamp.newt.event.KeyEvent.VK_TILDE;
//            case java.awt.event.KeyEvent.VK_DELETE        : return com.jogamp.newt.event.KeyEvent.VK_DELETE;
//            case java.awt.event.KeyEvent.VK_NUMPAD0       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD0;
//            case java.awt.event.KeyEvent.VK_NUMPAD1       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD1;
//            case java.awt.event.KeyEvent.VK_NUMPAD2       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD2;
//            case java.awt.event.KeyEvent.VK_NUMPAD3       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD3;
//            case java.awt.event.KeyEvent.VK_NUMPAD4       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD4;
//            case java.awt.event.KeyEvent.VK_NUMPAD5       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD5;
//            case java.awt.event.KeyEvent.VK_NUMPAD6       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD6;
//            case java.awt.event.KeyEvent.VK_NUMPAD7       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD7;
//            case java.awt.event.KeyEvent.VK_NUMPAD8       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD8;
//            case java.awt.event.KeyEvent.VK_NUMPAD9       : return com.jogamp.newt.event.KeyEvent.VK_NUMPAD9;
//            case java.awt.event.KeyEvent.VK_DECIMAL       : return com.jogamp.newt.event.KeyEvent.VK_DECIMAL;
//            case java.awt.event.KeyEvent.VK_SEPARATOR     : return com.jogamp.newt.event.KeyEvent.VK_SEPARATOR;
//            case java.awt.event.KeyEvent.VK_ADD           : return com.jogamp.newt.event.KeyEvent.VK_ADD;
//            case java.awt.event.KeyEvent.VK_SUBTRACT      : return com.jogamp.newt.event.KeyEvent.VK_SUBTRACT;
//            case java.awt.event.KeyEvent.VK_MULTIPLY      : return com.jogamp.newt.event.KeyEvent.VK_MULTIPLY;
//            case java.awt.event.KeyEvent.VK_DIVIDE        : return com.jogamp.newt.event.KeyEvent.VK_DIVIDE;
//            case java.awt.event.KeyEvent.VK_NUM_LOCK      : return com.jogamp.newt.event.KeyEvent.VK_NUM_LOCK;
//            case java.awt.event.KeyEvent.VK_KP_LEFT       : /** Fall through intended .. */
//            case java.awt.event.KeyEvent.VK_LEFT          : return com.jogamp.newt.event.KeyEvent.VK_LEFT;
//            case java.awt.event.KeyEvent.VK_KP_UP         : /** Fall through intended .. */
//            case java.awt.event.KeyEvent.VK_UP            : return com.jogamp.newt.event.KeyEvent.VK_UP;
//            case java.awt.event.KeyEvent.VK_KP_RIGHT      : /** Fall through intended .. */
//            case java.awt.event.KeyEvent.VK_RIGHT         : return com.jogamp.newt.event.KeyEvent.VK_RIGHT;
//            case java.awt.event.KeyEvent.VK_KP_DOWN       : /** Fall through intended .. */
//            case java.awt.event.KeyEvent.VK_DOWN          : return com.jogamp.newt.event.KeyEvent.VK_DOWN;
//            case java.awt.event.KeyEvent.VK_CONTEXT_MENU  : return com.jogamp.newt.event.KeyEvent.VK_CONTEXT_MENU;
//            case java.awt.event.KeyEvent.VK_WINDOWS       : return com.jogamp.newt.event.KeyEvent.VK_WINDOWS;
//            case java.awt.event.KeyEvent.VK_META          : return com.jogamp.newt.event.KeyEvent.VK_META;
//            case java.awt.event.KeyEvent.VK_HELP          : return com.jogamp.newt.event.KeyEvent.VK_HELP;
//            case java.awt.event.KeyEvent.VK_COMPOSE       : return com.jogamp.newt.event.KeyEvent.VK_COMPOSE;
//            case java.awt.event.KeyEvent.VK_BEGIN         : return com.jogamp.newt.event.KeyEvent.VK_BEGIN;
//            case java.awt.event.KeyEvent.VK_STOP          : return com.jogamp.newt.event.KeyEvent.VK_STOP;
//            case java.awt.event.KeyEvent.VK_INVERTED_EXCLAMATION_MARK: return com.jogamp.newt.event.KeyEvent.VK_INVERTED_EXCLAMATION_MARK;
//            case java.awt.event.KeyEvent.VK_EURO_SIGN     : return com.jogamp.newt.event.KeyEvent.VK_EURO_SIGN;
//            case java.awt.event.KeyEvent.VK_CUT           : return com.jogamp.newt.event.KeyEvent.VK_CUT;
//            case java.awt.event.KeyEvent.VK_COPY          : return com.jogamp.newt.event.KeyEvent.VK_COPY;
//            case java.awt.event.KeyEvent.VK_PASTE         : return com.jogamp.newt.event.KeyEvent.VK_PASTE;
//            case java.awt.event.KeyEvent.VK_UNDO          : return com.jogamp.newt.event.KeyEvent.VK_UNDO;
//            case java.awt.event.KeyEvent.VK_AGAIN         : return com.jogamp.newt.event.KeyEvent.VK_AGAIN;
//            case java.awt.event.KeyEvent.VK_FIND          : return com.jogamp.newt.event.KeyEvent.VK_FIND;
//            case java.awt.event.KeyEvent.VK_PROPS         : return com.jogamp.newt.event.KeyEvent.VK_PROPS;
//            case java.awt.event.KeyEvent.VK_INPUT_METHOD_ON_OFF: return com.jogamp.newt.event.KeyEvent.VK_INPUT_METHOD_ON_OFF;
//            case java.awt.event.KeyEvent.VK_CODE_INPUT    : return com.jogamp.newt.event.KeyEvent.VK_CODE_INPUT;
//            case java.awt.event.KeyEvent.VK_ROMAN_CHARACTERS: return com.jogamp.newt.event.KeyEvent.VK_ROMAN_CHARACTERS;
//            case java.awt.event.KeyEvent.VK_ALL_CANDIDATES: return com.jogamp.newt.event.KeyEvent.VK_ALL_CANDIDATES;
//            case java.awt.event.KeyEvent.VK_PREVIOUS_CANDIDATE: return com.jogamp.newt.event.KeyEvent.VK_PREVIOUS_CANDIDATE;
//            case java.awt.event.KeyEvent.VK_ALPHANUMERIC  : return com.jogamp.newt.event.KeyEvent.VK_ALPHANUMERIC;
//            case java.awt.event.KeyEvent.VK_KATAKANA      : return com.jogamp.newt.event.KeyEvent.VK_KATAKANA;
//            case java.awt.event.KeyEvent.VK_HIRAGANA      : return com.jogamp.newt.event.KeyEvent.VK_HIRAGANA;
//            case java.awt.event.KeyEvent.VK_FULL_WIDTH    : return com.jogamp.newt.event.KeyEvent.VK_FULL_WIDTH;
//            case java.awt.event.KeyEvent.VK_HALF_WIDTH    : return com.jogamp.newt.event.KeyEvent.VK_HALF_WIDTH;
//            case java.awt.event.KeyEvent.VK_JAPANESE_KATAKANA: return com.jogamp.newt.event.KeyEvent.VK_JAPANESE_KATAKANA;
//            case java.awt.event.KeyEvent.VK_JAPANESE_HIRAGANA: return com.jogamp.newt.event.KeyEvent.VK_JAPANESE_HIRAGANA;
//            case java.awt.event.KeyEvent.VK_JAPANESE_ROMAN: return com.jogamp.newt.event.KeyEvent.VK_JAPANESE_ROMAN;
//            case java.awt.event.KeyEvent.VK_KANA_LOCK     : return com.jogamp.newt.event.KeyEvent.VK_KANA_LOCK;
//        }
//        return defNEWTKeyCode;
//    }

    /** from: https://github.com/JogAmp/jogl/blob/master/src/newt/classes/jogamp/newt/awt/event/AWTNewtEventFactory.java */
    public static int newtKeyCode2AWTKeyCode(short newtKeyCode) {
        int result = -1;
        int defAwtKeyCode = 0xFFFF & newtKeyCode;
        // FIXME: On X11 it results to 0xff7e w/ AWTRobot, which is wrong. 0xffea Alt_R is expected AFAIK.
        switch (newtKeyCode) {
            case com.jogamp.newt.event.KeyEvent.VK_HOME -> result = KeyEvent.VK_HOME;
            case com.jogamp.newt.event.KeyEvent.VK_END -> result = KeyEvent.VK_END;
            case com.jogamp.newt.event.KeyEvent.VK_FINAL -> result = KeyEvent.VK_FINAL;
            case com.jogamp.newt.event.KeyEvent.VK_PRINTSCREEN -> result = KeyEvent.VK_PRINTSCREEN;
            case com.jogamp.newt.event.KeyEvent.VK_BACK_SPACE -> result = KeyEvent.VK_BACK_SPACE;
            case com.jogamp.newt.event.KeyEvent.VK_TAB -> result = KeyEvent.VK_TAB;
            case com.jogamp.newt.event.KeyEvent.VK_ENTER -> result = KeyEvent.VK_ENTER;
            case com.jogamp.newt.event.KeyEvent.VK_PAGE_DOWN -> result = KeyEvent.VK_PAGE_DOWN;
            case com.jogamp.newt.event.KeyEvent.VK_CLEAR -> result = KeyEvent.VK_CLEAR;
            case com.jogamp.newt.event.KeyEvent.VK_SHIFT -> result = KeyEvent.VK_SHIFT;
            case com.jogamp.newt.event.KeyEvent.VK_PAGE_UP -> result = KeyEvent.VK_PAGE_UP;
            case com.jogamp.newt.event.KeyEvent.VK_CONTROL -> result = KeyEvent.VK_CONTROL;
            case com.jogamp.newt.event.KeyEvent.VK_ALT -> result = KeyEvent.VK_ALT;
            case com.jogamp.newt.event.KeyEvent.VK_ALT_GRAPH -> result = KeyEvent.VK_ALT_GRAPH;
            case com.jogamp.newt.event.KeyEvent.VK_CAPS_LOCK -> result = KeyEvent.VK_CAPS_LOCK;
            case com.jogamp.newt.event.KeyEvent.VK_PAUSE -> result = KeyEvent.VK_PAUSE;
            case com.jogamp.newt.event.KeyEvent.VK_SCROLL_LOCK -> result = KeyEvent.VK_SCROLL_LOCK;
            case com.jogamp.newt.event.KeyEvent.VK_CANCEL -> result = KeyEvent.VK_CANCEL;
            case com.jogamp.newt.event.KeyEvent.VK_INSERT -> result = KeyEvent.VK_INSERT;
            case com.jogamp.newt.event.KeyEvent.VK_ESCAPE -> result = KeyEvent.VK_ESCAPE;
            case com.jogamp.newt.event.KeyEvent.VK_CONVERT -> result = KeyEvent.VK_CONVERT;
            case com.jogamp.newt.event.KeyEvent.VK_NONCONVERT -> result = KeyEvent.VK_NONCONVERT;
            case com.jogamp.newt.event.KeyEvent.VK_ACCEPT -> result = KeyEvent.VK_ACCEPT;
            case com.jogamp.newt.event.KeyEvent.VK_MODECHANGE -> result = KeyEvent.VK_MODECHANGE;
            case com.jogamp.newt.event.KeyEvent.VK_SPACE -> result = KeyEvent.VK_SPACE;
            case com.jogamp.newt.event.KeyEvent.VK_EXCLAMATION_MARK -> result = KeyEvent.VK_EXCLAMATION_MARK;
            case com.jogamp.newt.event.KeyEvent.VK_QUOTEDBL -> result = KeyEvent.VK_QUOTEDBL;
            case com.jogamp.newt.event.KeyEvent.VK_NUMBER_SIGN -> result = KeyEvent.VK_NUMBER_SIGN;
            case com.jogamp.newt.event.KeyEvent.VK_DOLLAR -> result = KeyEvent.VK_DOLLAR;
            case com.jogamp.newt.event.KeyEvent.VK_PERCENT, com.jogamp.newt.event.KeyEvent.VK_PIPE, com.jogamp.newt.event.KeyEvent.VK_QUESTIONMARK -> result = defAwtKeyCode;
            case com.jogamp.newt.event.KeyEvent.VK_AMPERSAND -> result = KeyEvent.VK_AMPERSAND;
            case com.jogamp.newt.event.KeyEvent.VK_QUOTE -> result = KeyEvent.VK_QUOTE;
            case com.jogamp.newt.event.KeyEvent.VK_LEFT_PARENTHESIS -> result = KeyEvent.VK_LEFT_PARENTHESIS;
            case com.jogamp.newt.event.KeyEvent.VK_RIGHT_PARENTHESIS -> result = KeyEvent.VK_RIGHT_PARENTHESIS;
            case com.jogamp.newt.event.KeyEvent.VK_ASTERISK -> result = KeyEvent.VK_ASTERISK;
            case com.jogamp.newt.event.KeyEvent.VK_PLUS -> result = KeyEvent.VK_PLUS;
            case com.jogamp.newt.event.KeyEvent.VK_COMMA -> result = KeyEvent.VK_COMMA;
            case com.jogamp.newt.event.KeyEvent.VK_MINUS -> result = KeyEvent.VK_MINUS;
            case com.jogamp.newt.event.KeyEvent.VK_PERIOD -> result = KeyEvent.VK_PERIOD;
            case com.jogamp.newt.event.KeyEvent.VK_SLASH -> result = KeyEvent.VK_SLASH;
            case com.jogamp.newt.event.KeyEvent.VK_0 -> result = KeyEvent.VK_0;
            case com.jogamp.newt.event.KeyEvent.VK_1 -> result = KeyEvent.VK_1;
            case com.jogamp.newt.event.KeyEvent.VK_2 -> result = KeyEvent.VK_2;
            case com.jogamp.newt.event.KeyEvent.VK_3 -> result = KeyEvent.VK_3;
            case com.jogamp.newt.event.KeyEvent.VK_4 -> result = KeyEvent.VK_4;
            case com.jogamp.newt.event.KeyEvent.VK_5 -> result = KeyEvent.VK_5;
            case com.jogamp.newt.event.KeyEvent.VK_6 -> result = KeyEvent.VK_6;
            case com.jogamp.newt.event.KeyEvent.VK_7 -> result = KeyEvent.VK_7;
            case com.jogamp.newt.event.KeyEvent.VK_8 -> result = KeyEvent.VK_8;
            case com.jogamp.newt.event.KeyEvent.VK_9 -> result = KeyEvent.VK_9;
            case com.jogamp.newt.event.KeyEvent.VK_COLON -> result = KeyEvent.VK_COLON;
            case com.jogamp.newt.event.KeyEvent.VK_SEMICOLON -> result = KeyEvent.VK_SEMICOLON;
            case com.jogamp.newt.event.KeyEvent.VK_LESS -> result = KeyEvent.VK_LESS;
            case com.jogamp.newt.event.KeyEvent.VK_EQUALS -> result = KeyEvent.VK_EQUALS;
            case com.jogamp.newt.event.KeyEvent.VK_GREATER -> result = KeyEvent.VK_GREATER;
            case com.jogamp.newt.event.KeyEvent.VK_AT -> result = KeyEvent.VK_AT;
            case com.jogamp.newt.event.KeyEvent.VK_A -> result = KeyEvent.VK_A;
            case com.jogamp.newt.event.KeyEvent.VK_B -> result = KeyEvent.VK_B;
            case com.jogamp.newt.event.KeyEvent.VK_C -> result = KeyEvent.VK_C;
            case com.jogamp.newt.event.KeyEvent.VK_D -> result = KeyEvent.VK_D;
            case com.jogamp.newt.event.KeyEvent.VK_E -> result = KeyEvent.VK_E;
            case com.jogamp.newt.event.KeyEvent.VK_F -> result = KeyEvent.VK_F;
            case com.jogamp.newt.event.KeyEvent.VK_G -> result = KeyEvent.VK_G;
            case com.jogamp.newt.event.KeyEvent.VK_H -> result = KeyEvent.VK_H;
            case com.jogamp.newt.event.KeyEvent.VK_I -> result = KeyEvent.VK_I;
            case com.jogamp.newt.event.KeyEvent.VK_J -> result = KeyEvent.VK_J;
            case com.jogamp.newt.event.KeyEvent.VK_K -> result = KeyEvent.VK_K;
            case com.jogamp.newt.event.KeyEvent.VK_L -> result = KeyEvent.VK_L;
            case com.jogamp.newt.event.KeyEvent.VK_M -> result = KeyEvent.VK_M;
            case com.jogamp.newt.event.KeyEvent.VK_N -> result = KeyEvent.VK_N;
            case com.jogamp.newt.event.KeyEvent.VK_O -> result = KeyEvent.VK_O;
            case com.jogamp.newt.event.KeyEvent.VK_P -> result = KeyEvent.VK_P;
            case com.jogamp.newt.event.KeyEvent.VK_Q -> result = KeyEvent.VK_Q;
            case com.jogamp.newt.event.KeyEvent.VK_R -> result = KeyEvent.VK_R;
            case com.jogamp.newt.event.KeyEvent.VK_S -> result = KeyEvent.VK_S;
            case com.jogamp.newt.event.KeyEvent.VK_T -> result = KeyEvent.VK_T;
            case com.jogamp.newt.event.KeyEvent.VK_U -> result = KeyEvent.VK_U;
            case com.jogamp.newt.event.KeyEvent.VK_V -> result = KeyEvent.VK_V;
            case com.jogamp.newt.event.KeyEvent.VK_W -> result = KeyEvent.VK_W;
            case com.jogamp.newt.event.KeyEvent.VK_X -> result = KeyEvent.VK_X;
            case com.jogamp.newt.event.KeyEvent.VK_Y -> result = KeyEvent.VK_Y;
            case com.jogamp.newt.event.KeyEvent.VK_Z -> result = KeyEvent.VK_Z;
            case com.jogamp.newt.event.KeyEvent.VK_OPEN_BRACKET -> result = KeyEvent.VK_OPEN_BRACKET;
            case com.jogamp.newt.event.KeyEvent.VK_BACK_SLASH -> result = KeyEvent.VK_BACK_SLASH;
            case com.jogamp.newt.event.KeyEvent.VK_CLOSE_BRACKET -> result = KeyEvent.VK_CLOSE_BRACKET;
            case com.jogamp.newt.event.KeyEvent.VK_CIRCUMFLEX -> result = KeyEvent.VK_CIRCUMFLEX;
            case com.jogamp.newt.event.KeyEvent.VK_UNDERSCORE -> result = KeyEvent.VK_UNDERSCORE;
            case com.jogamp.newt.event.KeyEvent.VK_BACK_QUOTE -> result = KeyEvent.VK_BACK_QUOTE;
            case com.jogamp.newt.event.KeyEvent.VK_F1 -> result = KeyEvent.VK_F1;
            case com.jogamp.newt.event.KeyEvent.VK_F2 -> result = KeyEvent.VK_F2;
            case com.jogamp.newt.event.KeyEvent.VK_F3 -> result = KeyEvent.VK_F3;
            case com.jogamp.newt.event.KeyEvent.VK_F4 -> result = KeyEvent.VK_F4;
            case com.jogamp.newt.event.KeyEvent.VK_F5 -> result = KeyEvent.VK_F5;
            case com.jogamp.newt.event.KeyEvent.VK_F6 -> result = KeyEvent.VK_F6;
            case com.jogamp.newt.event.KeyEvent.VK_F7 -> result = KeyEvent.VK_F7;
            case com.jogamp.newt.event.KeyEvent.VK_F8 -> result = KeyEvent.VK_F8;
            case com.jogamp.newt.event.KeyEvent.VK_F9 -> result = KeyEvent.VK_F9;
            case com.jogamp.newt.event.KeyEvent.VK_F10 -> result = KeyEvent.VK_F10;
            case com.jogamp.newt.event.KeyEvent.VK_F11 -> result = KeyEvent.VK_F11;
            case com.jogamp.newt.event.KeyEvent.VK_F12 -> result = KeyEvent.VK_F12;
            case com.jogamp.newt.event.KeyEvent.VK_F13 -> result = KeyEvent.VK_F13;
            case com.jogamp.newt.event.KeyEvent.VK_F14 -> result = KeyEvent.VK_F14;
            case com.jogamp.newt.event.KeyEvent.VK_F15 -> result = KeyEvent.VK_F15;
            case com.jogamp.newt.event.KeyEvent.VK_F16 -> result = KeyEvent.VK_F16;
            case com.jogamp.newt.event.KeyEvent.VK_F17 -> result = KeyEvent.VK_F17;
            case com.jogamp.newt.event.KeyEvent.VK_F18 -> result = KeyEvent.VK_F18;
            case com.jogamp.newt.event.KeyEvent.VK_F19 -> result = KeyEvent.VK_F19;
            case com.jogamp.newt.event.KeyEvent.VK_F20 -> result = KeyEvent.VK_F20;
            case com.jogamp.newt.event.KeyEvent.VK_F21 -> result = KeyEvent.VK_F21;
            case com.jogamp.newt.event.KeyEvent.VK_F22 -> result = KeyEvent.VK_F22;
            case com.jogamp.newt.event.KeyEvent.VK_F23 -> result = KeyEvent.VK_F23;
            case com.jogamp.newt.event.KeyEvent.VK_F24 -> result = KeyEvent.VK_F24;
            case com.jogamp.newt.event.KeyEvent.VK_LEFT_BRACE -> result = KeyEvent.VK_BRACELEFT;
            case com.jogamp.newt.event.KeyEvent.VK_RIGHT_BRACE -> result = KeyEvent.VK_BRACERIGHT;
            case com.jogamp.newt.event.KeyEvent.VK_TILDE -> result = KeyEvent.VK_DEAD_TILDE;
            case com.jogamp.newt.event.KeyEvent.VK_DELETE -> result = KeyEvent.VK_DELETE;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD0 -> result = KeyEvent.VK_NUMPAD0;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD1 -> result = KeyEvent.VK_NUMPAD1;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD2 -> result = KeyEvent.VK_NUMPAD2;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD3 -> result = KeyEvent.VK_NUMPAD3;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD4 -> result = KeyEvent.VK_NUMPAD4;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD5 -> result = KeyEvent.VK_NUMPAD5;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD6 -> result = KeyEvent.VK_NUMPAD6;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD7 -> result = KeyEvent.VK_NUMPAD7;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD8 -> result = KeyEvent.VK_NUMPAD8;
            case com.jogamp.newt.event.KeyEvent.VK_NUMPAD9 -> result = KeyEvent.VK_NUMPAD9;
            case com.jogamp.newt.event.KeyEvent.VK_DECIMAL -> result = KeyEvent.VK_DECIMAL;
            case com.jogamp.newt.event.KeyEvent.VK_SEPARATOR -> result = KeyEvent.VK_SEPARATOR;
            case com.jogamp.newt.event.KeyEvent.VK_ADD -> result = KeyEvent.VK_ADD;
            case com.jogamp.newt.event.KeyEvent.VK_SUBTRACT -> result = KeyEvent.VK_SUBTRACT;
            case com.jogamp.newt.event.KeyEvent.VK_MULTIPLY -> result = KeyEvent.VK_MULTIPLY;
            case com.jogamp.newt.event.KeyEvent.VK_DIVIDE -> result = KeyEvent.VK_DIVIDE;
            case com.jogamp.newt.event.KeyEvent.VK_NUM_LOCK -> result = KeyEvent.VK_NUM_LOCK;
            case com.jogamp.newt.event.KeyEvent.VK_LEFT -> result = KeyEvent.VK_LEFT;
            case com.jogamp.newt.event.KeyEvent.VK_UP -> result = KeyEvent.VK_UP;
            case com.jogamp.newt.event.KeyEvent.VK_RIGHT -> result = KeyEvent.VK_RIGHT;
            case com.jogamp.newt.event.KeyEvent.VK_DOWN -> result = KeyEvent.VK_DOWN;
            case com.jogamp.newt.event.KeyEvent.VK_CONTEXT_MENU -> result = KeyEvent.VK_CONTEXT_MENU;
            case com.jogamp.newt.event.KeyEvent.VK_WINDOWS -> result = KeyEvent.VK_WINDOWS;
            case com.jogamp.newt.event.KeyEvent.VK_META -> result = KeyEvent.VK_META;
            case com.jogamp.newt.event.KeyEvent.VK_HELP -> result = KeyEvent.VK_HELP;
            case com.jogamp.newt.event.KeyEvent.VK_COMPOSE -> result = KeyEvent.VK_COMPOSE;
            case com.jogamp.newt.event.KeyEvent.VK_BEGIN -> result = KeyEvent.VK_BEGIN;
            case com.jogamp.newt.event.KeyEvent.VK_STOP -> result = KeyEvent.VK_STOP;
            case com.jogamp.newt.event.KeyEvent.VK_INVERTED_EXCLAMATION_MARK -> result = KeyEvent.VK_INVERTED_EXCLAMATION_MARK;
            case com.jogamp.newt.event.KeyEvent.VK_EURO_SIGN -> result = KeyEvent.VK_EURO_SIGN;
            case com.jogamp.newt.event.KeyEvent.VK_CUT -> result = KeyEvent.VK_CUT;
            case com.jogamp.newt.event.KeyEvent.VK_COPY -> result = KeyEvent.VK_COPY;
            case com.jogamp.newt.event.KeyEvent.VK_PASTE -> result = KeyEvent.VK_PASTE;
            case com.jogamp.newt.event.KeyEvent.VK_UNDO -> result = KeyEvent.VK_UNDO;
            case com.jogamp.newt.event.KeyEvent.VK_AGAIN -> result = KeyEvent.VK_AGAIN;
            case com.jogamp.newt.event.KeyEvent.VK_FIND -> result = KeyEvent.VK_FIND;
            case com.jogamp.newt.event.KeyEvent.VK_PROPS -> result = KeyEvent.VK_PROPS;
            case com.jogamp.newt.event.KeyEvent.VK_INPUT_METHOD_ON_OFF -> result = KeyEvent.VK_INPUT_METHOD_ON_OFF;
            case com.jogamp.newt.event.KeyEvent.VK_CODE_INPUT -> result = KeyEvent.VK_CODE_INPUT;
            case com.jogamp.newt.event.KeyEvent.VK_ROMAN_CHARACTERS -> result = KeyEvent.VK_ROMAN_CHARACTERS;
            case com.jogamp.newt.event.KeyEvent.VK_ALL_CANDIDATES -> result = KeyEvent.VK_ALL_CANDIDATES;
            case com.jogamp.newt.event.KeyEvent.VK_PREVIOUS_CANDIDATE -> result = KeyEvent.VK_PREVIOUS_CANDIDATE;
            case com.jogamp.newt.event.KeyEvent.VK_ALPHANUMERIC -> result = KeyEvent.VK_ALPHANUMERIC;
            case com.jogamp.newt.event.KeyEvent.VK_KATAKANA -> result = KeyEvent.VK_KATAKANA;
            case com.jogamp.newt.event.KeyEvent.VK_HIRAGANA -> result = KeyEvent.VK_HIRAGANA;
            case com.jogamp.newt.event.KeyEvent.VK_FULL_WIDTH -> result = KeyEvent.VK_FULL_WIDTH;
            case com.jogamp.newt.event.KeyEvent.VK_HALF_WIDTH -> result = KeyEvent.VK_HALF_WIDTH;
            case com.jogamp.newt.event.KeyEvent.VK_JAPANESE_KATAKANA -> result = KeyEvent.VK_JAPANESE_KATAKANA;
            case com.jogamp.newt.event.KeyEvent.VK_JAPANESE_HIRAGANA -> result = KeyEvent.VK_JAPANESE_HIRAGANA;
            case com.jogamp.newt.event.KeyEvent.VK_JAPANESE_ROMAN -> result = KeyEvent.VK_JAPANESE_ROMAN;
            case com.jogamp.newt.event.KeyEvent.VK_KANA_LOCK -> result = KeyEvent.VK_KANA_LOCK;
        }
        if (result == -1) {
            result = defAwtKeyCode;
        }
        return result;
    }

}
